### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by wokalski** [BuckleTypes/bs-react-native#13]
When contributors show up, probably mostly from the JS community they are going to need some advice. 

1. References to langauge manual (and probably RWO)
2. References to Buckelscript manual
3. Where to start (we probably will need something like `good first issue`)
4. Naming conventions
5. Development workflow (from my contributing experience this is particularly important to address)
6. Where to document stuff

**Comment by wokalski** [comment]
Some inspiration:
https://github.com/sympy/sympy/wiki/Development-workflow

**Comment by kennetpostigo** [comment]
@wokalski @saschatimme I'm building a medium to large size app and i'm going to use `bs-react-native` for it. this would be really useful when sending PR's for missing RN components/api's

**Comment by saschatimme** [comment]
Just made a [PR](#42) with a rough first draft. Maybe you could take a look @kennetpostigo and say if this would be useful enough for you.

**Comment by saschatimme** [comment]
I will close this for now, since we merged the PR.
