### ISSUE TITLE
Onboarding guide

### ISSUE THREAD

**Issue by wokalski** [BuckleTypes/bs-react-native#15]
OK, this is far fetched but I imagine that we could somehow integrate our on boarding experience with Expo Snack or live preview akin React Native tutorial. It would be awesome if people could simply try this out live. What irks me about getting started guides nowadays is that they usually start with 

1. go download this
2. go install that
3. when you have a problem (AND YOU'RE DEFINITELY GOING TO HAVE ONE) browse issues in our repo

Ideally the sections in the on boarding guide would consist of interactive snippets. An awesome twist would be if we could somehow integrate `merlin` like functionality so that after a user hovers a symbol (module, function, type) a tooltip appears with a reference to it in the documentation.

**Comment by saschatimme** [comment]
Maybe its not so far fetched.
I already hacked something together for `create-react-app` https://github.com/saschatimme/reason-react-scripts. Maybe we could something like that bring into `create-react-native-app` :)

**Comment by wokalski** [comment]
oh, awesome. For now it would be less work than a web based thing. We could structure the example app to reflect the directory layout of its source. Then it would relatively easy for the users to navigate through corresponding sections.

**Comment by saschatimme** [comment]
I think that's so far covered with the Readme, I think the hacking into `create-react-native-app` is for another day :)

**Comment by tonyhb** [comment]
👍 the only thing i'd add to the readme is that, on mac/linux, ninja needs to be installed prior to installing the yarn packages for bucklescript;  if not, it'll always fail with a ninja error.  I'll make a PR soon :)
