### ISSUE TITLE
Integrate UIExplorer App

### ISSUE THREAD

**Issue by saschatimme** [BuckleTypes/bs-react-native#16]
From our (mine and @wokalski) its not sufficient to just write the bindings and you are done. We need a proper test enviroment. Therefore I would propose to integrate https://github.com/saschatimme/reason-ui-explorer in our repo.

**Comment by wokalski** [comment]
just do it! One thing to consider - we should minimise the amount of steps needed to start the app and `bsb` watcher. We need to optimise it in regards to #13. It'd ideally be:
```
1st tab:
npm run start-rn
2nd tab:
npm run start-re
3rd tab:
react-native run-[ios|android]
```

**Comment by saschatimme** [comment]
Maybe we could come up with some node scripts which would just pop up multiple windows (think of the RN Packager window)

**Comment by wokalski** [comment]
I hate it :D. But yeah - beginner friendly `npm start` could do that.
