### ISSUE TITLE
Suggest using in source builds for easier asset usage

### ISSUE THREAD

**Issue by wokalski** [BuckleTypes/bs-react-native#183]
Good point from https://github.com/knowbody/reroute-native/issues/83 by @grsabreu.

**Comment by grabbou** [comment]
This has been done in Rebolt back in the day -> https://github.com/callstackincubator/rebolt-navigation/pull/87/files.

Is there anything we should do in this issue? I believe our documentation contains suggestion for doing so, so this issue can be closed if that's the case.

**Comment by wokalski** [comment]
if there's a note about it in docs - we're good.
