### ISSUE TITLE
Navigation library

### ISSUE THREAD

**Issue by wokalski** [BuckleTypes/bs-react-native#6]
Every nontrivial apps needs to handle navigation somehow. We need to pick one of the libraries available and ideally PR a bsconfig & typings to it. I'm rooting for `react-navigation` not because it's ideal but because I think they are likely to accept a `.bsconfig` contribution and it uses Flow.

**Comment by saschatimme** [comment]
I started bindings to `react-navigation` [here](https://github.com/saschatimme/bs-react-navigation).
The bindings will end in a separate repo, therefore I close the issue here.

**Comment by aloifolia** [comment]
So whats the state of react native navigation with Reason? Any progress so far?

**Comment by MoOx** [comment]
Like said on the comment above yours, see https://github.com/saschatimme/bs-react-navigation

**Comment by saschatimme** [comment]
I am really not happy with the state of these bindings and would rather recommend to check out
https://github.com/szymonzmyslony/reason-react-native-navigation

**Comment by Maushundb** [comment]
+1 on this - there doesn't seem to be any repos that have been touched in the past year.

**Comment by MoOx** [comment]
Something is coming... Probably after the incoming reason-react-native :)
